name: Localhost CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - run: |
        sudo docker stop my-node-app || true
        sudo docker rm my-node-app || true

    - run: sudo docker build -t my-node-app .

    - run: sudo docker run -d -p 3000:3000 --name my-node-app my-node-app
